In [1]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive

In [2]:
maths_path = "/content/drive/MyDrive/Student_Performance_Project/data/raw/Maths.csv"

portuguese_path = "/content/drive/MyDrive/Student_Performance_Project/data/raw/Portuguese.csv"

factors_path = "/content/drive/MyDrive/Student_Performance_Project/data/raw/StudentPerformanceFactors.csv"

In [9]:
import pandas as pd
import csv

math_df = pd.read_csv(maths_path, encoding='latin1', delimiter=';', engine='python', quoting=csv.QUOTE_NONE, on_bad_lines='skip')

port_df = pd.read_csv(portuguese_path, encoding='latin1', delimiter=';', engine='python', quoting=csv.QUOTE_NONE, on_bad_lines='skip')

factor_df = pd.read_csv(factors_path, encoding='latin1', delimiter=';', engine='python', quoting=csv.QUOTE_NONE, on_bad_lines='skip')

In [18]:
!pip install openpyxl

Requirement already satisfied: openpyxl in /usr/local/lib/python3.12/dist-packages (3.1.5)
Requirement already satisfied: et-xmlfile in /usr/local/lib/python3.12/dist-packages (from openpyxl) (2.0.0)

In [21]:
import pandas as pd

# Excel files
math_df = pd.read_excel(
    "/content/drive/MyDrive/Student_Performance_Project/data/raw/Maths.csv",
    engine="openpyxl"
)

port_df = pd.read_excel(
    "/content/drive/MyDrive/Student_Performance_Project/data/raw/Portuguese.csv",
    engine="openpyxl"
)

# Actual CSV file
factor_df = pd.read_csv(
    "/content/drive/MyDrive/Student_Performance_Project/data/raw/StudentPerformanceFactors.csv"
)

display(math_df.head())
display(port_df.head())
display(factor_df.head())

,school,sex,age,address,famsize,Pstatus,Medu,Fedu,Mjob,Fjob,...,famrel,freetime,goout,Dalc,Walc,health,absences,G1,G2,G3
0,GP,F,18,U,GT3,A,4,4,at_home,teacher,...,4,3,4,1,1,3,6,5,6,6
1,GP,F,17,U,GT3,T,1,1,at_home,other,...,5,3,3,1,1,3,4,5,5,6
2,GP,F,15,U,LE3,T,1,1,at_home,other,...,4,3,2,2,3,3,10,7,8,10
3,GP,F,15,U,GT3,T,4,2,health,services,...,3,2,2,1,1,5,2,15,14,15
4,GP,F,16,U,GT3,T,3,3,other,other,...,4,3,2,1,2,5,4,6,10,10

,school,sex,age,address,famsize,Pstatus,Medu,Fedu,Mjob,Fjob,...,famrel,freetime,goout,Dalc,Walc,health,absences,G1,G2,G3
0,GP,F,18,U,GT3,A,4,4,at_home,teacher,...,4,3,4,1,1,3,4,0,11,11
1,GP,F,17,U,GT3,T,1,1,at_home,other,...,5,3,3,1,1,3,2,9,11,11
2,GP,F,15,U,LE3,T,1,1,at_home,other,...,4,3,2,2,3,3,6,12,13,12
3,GP,F,15,U,GT3,T,4,2,health,services,...,3,2,2,1,1,5,0,14,14,14
4,GP,F,16,U,GT3,T,3,3,other,other,...,4,3,2,1,2,5,0,11,13,13

,Hours_Studied,Attendance,Parental_Involvement,Access_to_Resources,Extracurricular_Activities,Sleep_Hours,Previous_Scores,Motivation_Level,Internet_Access,Tutoring_Sessions,Family_Income,Teacher_Quality,School_Type,Peer_Influence,Physical_Activity,Learning_Disabilities,Parental_Education_Level,Distance_from_Home,Gender,Exam_Score
0,23,84,Low,High,No,7,73,Low,Yes,0,Low,Medium,Public,Positive,3,No,High School,Near,Male,67
1,19,64,Low,Medium,No,8,59,Low,Yes,2,Medium,Medium,Public,Negative,4,No,College,Moderate,Female,61
2,24,98,Medium,Medium,Yes,7,91,Medium,Yes,2,Medium,Medium,Public,Neutral,4,No,Postgraduate,Near,Male,74
3,29,89,Low,Medium,Yes,8,98,Medium,Yes,1,Medium,Medium,Public,Negative,4,No,High School,Moderate,Male,71
4,19,92,Medium,Medium,Yes,6,65,Medium,Yes,3,Medium,High,Public,Neutral,4,No,College,Near,Female,70

In [22]:
print("========== Maths Dataset ==========")
display(math_df.head())

print("\n========== Portuguese Dataset ==========")
display(port_df.head())

print("\n========== Student Performance Factors Dataset ==========")
display(factor_df.head())

========== Maths Dataset ==========

,school,sex,age,address,famsize,Pstatus,Medu,Fedu,Mjob,Fjob,...,famrel,freetime,goout,Dalc,Walc,health,absences,G1,G2,G3
0,GP,F,18,U,GT3,A,4,4,at_home,teacher,...,4,3,4,1,1,3,6,5,6,6
1,GP,F,17,U,GT3,T,1,1,at_home,other,...,5,3,3,1,1,3,4,5,5,6
2,GP,F,15,U,LE3,T,1,1,at_home,other,...,4,3,2,2,3,3,10,7,8,10
3,GP,F,15,U,GT3,T,4,2,health,services,...,3,2,2,1,1,5,2,15,14,15
4,GP,F,16,U,GT3,T,3,3,other,other,...,4,3,2,1,2,5,4,6,10,10

========== Portuguese Dataset ==========

,school,sex,age,address,famsize,Pstatus,Medu,Fedu,Mjob,Fjob,...,famrel,freetime,goout,Dalc,Walc,health,absences,G1,G2,G3
0,GP,F,18,U,GT3,A,4,4,at_home,teacher,...,4,3,4,1,1,3,4,0,11,11
1,GP,F,17,U,GT3,T,1,1,at_home,other,...,5,3,3,1,1,3,2,9,11,11
2,GP,F,15,U,LE3,T,1,1,at_home,other,...,4,3,2,2,3,3,6,12,13,12
3,GP,F,15,U,GT3,T,4,2,health,services,...,3,2,2,1,1,5,0,14,14,14
4,GP,F,16,U,GT3,T,3,3,other,other,...,4,3,2,1,2,5,0,11,13,13

========== Student Performance Factors Dataset ==========

,Hours_Studied,Attendance,Parental_Involvement,Access_to_Resources,Extracurricular_Activities,Sleep_Hours,Previous_Scores,Motivation_Level,Internet_Access,Tutoring_Sessions,Family_Income,Teacher_Quality,School_Type,Peer_Influence,Physical_Activity,Learning_Disabilities,Parental_Education_Level,Distance_from_Home,Gender,Exam_Score
0,23,84,Low,High,No,7,73,Low,Yes,0,Low,Medium,Public,Positive,3,No,High School,Near,Male,67
1,19,64,Low,Medium,No,8,59,Low,Yes,2,Medium,Medium,Public,Negative,4,No,College,Moderate,Female,61
2,24,98,Medium,Medium,Yes,7,91,Medium,Yes,2,Medium,Medium,Public,Neutral,4,No,Postgraduate,Near,Male,74
3,29,89,Low,Medium,Yes,8,98,Medium,Yes,1,Medium,Medium,Public,Negative,4,No,High School,Moderate,Male,71
4,19,92,Medium,Medium,Yes,6,65,Medium,Yes,3,Medium,High,Public,Neutral,4,No,College,Near,Female,70

In [23]:
print("========== Maths Dataset Columns ==========")
print(math_df.columns)

print("\n========== Portuguese Dataset Columns ==========")
print(port_df.columns)

print("\n========== Student Performance Factors Dataset Columns ==========")
print(factor_df.columns)

========== Maths Dataset Columns ==========
Index(['school', 'sex', 'age', 'address', 'famsize', 'Pstatus', 'Medu', 'Fedu',
       'Mjob', 'Fjob', 'reason', 'guardian', 'traveltime', 'studytime',
       'failures', 'schoolsup', 'famsup', 'paid', 'activities', 'nursery',
       'higher', 'internet', 'romantic', 'famrel', 'freetime', 'goout', 'Dalc',
       'Walc', 'health', 'absences', 'G1', 'G2', 'G3'],
      dtype='object')

========== Portuguese Dataset Columns ==========
Index(['school', 'sex', 'age', 'address', 'famsize', 'Pstatus', 'Medu', 'Fedu',
       'Mjob', 'Fjob', 'reason', 'guardian', 'traveltime', 'studytime',
       'failures', 'schoolsup', 'famsup', 'paid', 'activities', 'nursery',
       'higher', 'internet', 'romantic', 'famrel', 'freetime', 'goout', 'Dalc',
       'Walc', 'health', 'absences', 'G1', 'G2', 'G3'],
      dtype='object')

========== Student Performance Factors Dataset Columns ==========
Index(['Hours_Studied', 'Attendance', 'Parental_Involvement',
       'Access_to_Resources', 'Extracurricular_Activities', 'Sleep_Hours',
       'Previous_Scores', 'Motivation_Level', 'Internet_Access',
       'Tutoring_Sessions', 'Family_Income', 'Teacher_Quality', 'School_Type',
       'Peer_Influence', 'Physical_Activity', 'Learning_Disabilities',
       'Parental_Education_Level', 'Distance_from_Home', 'Gender',
       'Exam_Score'],
      dtype='object')

In [24]:
print("========== Dataset Shapes ==========")

print("Maths Dataset:", math_df.shape)

print("Portuguese Dataset:", port_df.shape)

print("Student Performance Factors Dataset:", factor_df.shape)

========== Dataset Shapes ==========
Maths Dataset: (397, 33)
Portuguese Dataset: (651, 33)
Student Performance Factors Dataset: (6607, 20)

In [25]:
print("========== Maths Dataset ==========")
math_df.info()

print("\n========== Portuguese Dataset ==========")
port_df.info()

print("\n========== Student Performance Factors Dataset ==========")
factor_df.info()

========== Maths Dataset ==========
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 397 entries, 0 to 396
Data columns (total 33 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   school      397 non-null    object
 1   sex         397 non-null    object
 2   age         397 non-null    int64
 3   address     397 non-null    object
 4   famsize     397 non-null    object
 5   Pstatus     397 non-null    object
 6   Medu        397 non-null    int64
 7   Fedu        397 non-null    int64
 8   Mjob        397 non-null    object
 9   Fjob        397 non-null    object
 10  reason      397 non-null    object
 11  guardian    397 non-null    object
 12  traveltime  397 non-null    int64
 13  studytime   397 non-null    int64
 14  failures    397 non-null    int64
 15  schoolsup   397 non-null    object
 16  famsup      397 non-null    object
 17  paid        397 non-null    object
 18  activities  397 non-null    object
 19  nursery     397 non-null    object
 20  higher      397 non-null    object
 21  internet    397 non-null    object
 22  romantic    397 non-null    object
 23  famrel      397 non-null    int64
 24  freetime    397 non-null    int64
 25  goout       397 non-null    int64
 26  Dalc        397 non-null    int64
 27  Walc        397 non-null    int64
 28  health      397 non-null    int64
 29  absences    397 non-null    int64
 30  G1          397 non-null    int64
 31  G2          397 non-null    int64
 32  G3          397 non-null    int64
dtypes: int64(16), object(17)
memory usage: 102.5+ KB

========== Portuguese Dataset ==========
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 651 entries, 0 to 650
Data columns (total 33 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   school      651 non-null    object
 1   sex         651 non-null    object
 2   age         651 non-null    int64
 3   address     651 non-null    object
 4   famsize     651 non-null    object
 5   Pstatus     651 non-null    object
 6   Medu        651 non-null    int64
 7   Fedu        651 non-null    int64
 8   Mjob        651 non-null    object
 9   Fjob        651 non-null    object
 10  reason      651 non-null    object
 11  guardian    651 non-null    object
 12  traveltime  651 non-null    int64
 13  studytime   651 non-null    int64
 14  failures    651 non-null    int64
 15  schoolsup   651 non-null    object
 16  famsup      651 non-null    object
 17  paid        651 non-null    object
 18  activities  651 non-null    object
 19  nursery     651 non-null    object
 20  higher      651 non-null    object
 21  internet    651 non-null    object
 22  romantic    651 non-null    object
 23  famrel      651 non-null    int64
 24  freetime    651 non-null    int64
 25  goout       651 non-null    int64
 26  Dalc        651 non-null    int64
 27  Walc        651 non-null    int64
 28  health      651 non-null    int64
 29  absences    651 non-null    int64
 30  G1          651 non-null    int64
 31  G2          651 non-null    int64
 32  G3          651 non-null    int64
dtypes: int64(16), object(17)
memory usage: 168.0+ KB

========== Student Performance Factors Dataset ==========
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 6607 entries, 0 to 6606
Data columns (total 20 columns):
 #   Column                      Non-Null Count  Dtype
---  ------                      --------------  -----
 0   Hours_Studied               6607 non-null   int64
 1   Attendance                  6607 non-null   int64
 2   Parental_Involvement        6607 non-null   object
 3   Access_to_Resources         6607 non-null   object
 4   Extracurricular_Activities  6607 non-null   object
 5   Sleep_Hours                 6607 non-null   int64
 6   Previous_Scores             6607 non-null   int64
 7   Motivation_Level            6607 non-null   object
 8   Internet_Access             6607 non-null   object
 9   Tutoring_Sessions           6607 non-null   int64
 10  Family_Income               6607 non-null   object
 11  Teacher_Quality             6529 non-null   object
 12  School_Type                 6607 non-null   object
 13  Peer_Influence              6607 non-null   object
 14  Physical_Activity           6607 non-null   int64
 15  Learning_Disabilities       6607 non-null   object
 16  Parental_Education_Level    6517 non-null   object
 17  Distance_from_Home          6540 non-null   object
 18  Gender                      6607 non-null   object
 19  Exam_Score                  6607 non-null   int64
dtypes: int64(7), object(13)
memory usage: 1.0+ MB

In [26]:
print("========== Missing Values ==========")

print("\nMaths Dataset")
print(math_df.isnull().sum())

print("\nPortuguese Dataset")
print(port_df.isnull().sum())

print("\nStudent Performance Factors Dataset")
print(factor_df.isnull().sum())

========== Missing Values ==========

Maths Dataset
school        0
sex           0
age           0
address       0
famsize       0
Pstatus       0
Medu          0
Fedu          0
Mjob          0
Fjob          0
reason        0
guardian      0
traveltime    0
studytime     0
failures      0
schoolsup     0
famsup        0
paid          0
activities    0
nursery       0
higher        0
internet      0
romantic      0
famrel        0
freetime      0
goout         0
Dalc          0
Walc          0
health        0
absences      0
G1            0
G2            0
G3            0
dtype: int64

Portuguese Dataset
school        0
sex           0
age           0
address       0
famsize       0
Pstatus       0
Medu          0
Fedu          0
Mjob          0
Fjob          0
reason        0
guardian      0
traveltime    0
studytime     0
failures      0
schoolsup     0
famsup        0
paid          0
activities    0
nursery       0
higher        0
internet      0
romantic      0
famrel        0
freetime      0
goout         0
Dalc          0
Walc          0
health        0
absences      0
G1            0
G2            0
G3            0
dtype: int64

Student Performance Factors Dataset
Hours_Studied                  0
Attendance                     0
Parental_Involvement           0
Access_to_Resources            0
Extracurricular_Activities     0
Sleep_Hours                    0
Previous_Scores                0
Motivation_Level               0
Internet_Access                0
Tutoring_Sessions              0
Family_Income                  0
Teacher_Quality               78
School_Type                    0
Peer_Influence                 0
Physical_Activity              0
Learning_Disabilities          0
Parental_Education_Level      90
Distance_from_Home            67
Gender                         0
Exam_Score                     0
dtype: int64

In [27]:
print("========== Maths Dataset ==========")
display(math_df.describe())

print("\n========== Portuguese Dataset ==========")
display(port_df.describe())

print("\n========== Student Performance Factors Dataset ==========")
display(factor_df.describe())

========== Maths Dataset ==========

,age,Medu,Fedu,traveltime,studytime,failures,famrel,freetime,goout,Dalc,Walc,health,absences,G1,G2,G3
count,397.000000,397.000000,397.000000,397.000000,397.000000,397.000000,397.000000,397.000000,397.000000,397.000000,397.000000,397.000000,397.000000,397.000000,397.000000,397.000000
mean,16.705290,2.748111,2.521411,1.450882,2.032746,0.335013,3.944584,3.234257,3.108312,1.478589,2.289673,3.556675,5.695214,10.881612,10.687657,10.377834
std,1.279716,1.097301,1.090672,0.696840,0.838731,0.742714,0.894400,0.996476,1.112762,0.889143,1.286770,1.388967,7.988015,3.333120,3.770322,4.604928
min,15.000000,0.000000,0.000000,1.000000,1.000000,0.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,0.000000,3.000000,0.000000,0.000000
25%,16.000000,2.000000,2.000000,1.000000,1.000000,0.000000,4.000000,3.000000,2.000000,1.000000,1.000000,3.000000,0.000000,8.000000,9.000000,8.000000
50%,17.000000,3.000000,2.000000,1.000000,2.000000,0.000000,4.000000,3.000000,3.000000,1.000000,2.000000,4.000000,4.000000,11.000000,11.000000,11.000000
75%,18.000000,4.000000,3.000000,2.000000,2.000000,0.000000,5.000000,4.000000,4.000000,2.000000,3.000000,5.000000,8.000000,13.000000,13.000000,14.000000
max,22.000000,4.000000,4.000000,4.000000,4.000000,3.000000,5.000000,5.000000,5.000000,5.000000,5.000000,5.000000,75.000000,19.000000,19.000000,20.000000

========== Portuguese Dataset ==========

,age,Medu,Fedu,traveltime,studytime,failures,famrel,freetime,goout,Dalc,Walc,health,absences,G1,G2,G3
count,651.000000,651.000000,651.000000,651.000000,651.000000,651.000000,651.000000,651.00000,651.000000,651.000000,651.000000,651.000000,651.000000,651.000000,651.000000,651.000000
mean,16.745008,2.516129,2.308756,1.569892,1.930876,0.221198,3.930876,3.18126,3.187404,1.500768,2.276498,3.537634,3.654378,11.382488,11.569892,11.904762
std,1.217609,1.134481,1.100308,0.747889,0.828241,0.592449,0.954253,1.04999,1.174824,0.923830,1.284362,1.445326,4.635853,2.777315,2.909287,3.225880
min,15.000000,0.000000,0.000000,1.000000,1.000000,0.000000,1.000000,1.00000,1.000000,1.000000,1.000000,1.000000,0.000000,0.000000,0.000000,0.000000
25%,16.000000,2.000000,1.000000,1.000000,1.000000,0.000000,4.000000,3.00000,2.000000,1.000000,1.000000,2.000000,0.000000,10.000000,10.000000,10.000000
50%,17.000000,2.000000,2.000000,1.000000,2.000000,0.000000,4.000000,3.00000,3.000000,1.000000,2.000000,4.000000,2.000000,11.000000,11.000000,12.000000
75%,18.000000,4.000000,3.000000,2.000000,2.000000,0.000000,5.000000,4.00000,4.000000,2.000000,3.000000,5.000000,6.000000,13.000000,13.000000,14.000000
max,22.000000,4.000000,4.000000,4.000000,4.000000,3.000000,5.000000,5.00000,5.000000,5.000000,5.000000,5.000000,32.000000,19.000000,19.000000,19.000000

========== Student Performance Factors Dataset ==========

,Hours_Studied,Attendance,Sleep_Hours,Previous_Scores,Tutoring_Sessions,Physical_Activity,Exam_Score
count,6607.000000,6607.000000,6607.00000,6607.000000,6607.000000,6607.000000,6607.000000
mean,19.975329,79.977448,7.02906,75.070531,1.493719,2.967610,67.235659
std,5.990594,11.547475,1.46812,14.399784,1.230570,1.031231,3.890456
min,1.000000,60.000000,4.00000,50.000000,0.000000,0.000000,55.000000
25%,16.000000,70.000000,6.00000,63.000000,1.000000,2.000000,65.000000
50%,20.000000,80.000000,7.00000,75.000000,1.000000,3.000000,67.000000
75%,24.000000,90.000000,8.00000,88.000000,2.000000,4.000000,69.000000
max,44.000000,100.000000,10.00000,100.000000,8.000000,6.000000,101.000000

In [28]:
print("========== Duplicate Records ==========")

print("Maths Dataset:", math_df.duplicated().sum())

print("Portuguese Dataset:", port_df.duplicated().sum())

print("Student Performance Factors Dataset:", factor_df.duplicated().sum())

========== Duplicate Records ==========
Maths Dataset: 2
Portuguese Dataset: 2
Student Performance Factors Dataset: 0

In [29]:
print("Rows and Columns")

print("Maths:", math_df.shape)

print("Portuguese:", port_df.shape)

print("Performance Factors:", factor_df.shape)

Rows and Columns
Maths: (397, 33)
Portuguese: (651, 33)
Performance Factors: (6607, 20)

In [30]:
print("========== Data Types ==========")

print(math_df.dtypes)

print(port_df.dtypes)

print(factor_df.dtypes)

========== Data Types ==========
school        object
sex           object
age            int64
address       object
famsize       object
Pstatus       object
Medu           int64
Fedu           int64
Mjob          object
Fjob          object
reason        object
guardian      object
traveltime     int64
studytime      int64
failures       int64
schoolsup     object
famsup        object
paid          object
activities    object
nursery       object
higher        object
internet      object
romantic      object
famrel         int64
freetime       int64
goout          int64
Dalc           int64
Walc           int64
health         int64
absences       int64
G1             int64
G2             int64
G3             int64
dtype: object
school        object
sex           object
age            int64
address       object
famsize       object
Pstatus       object
Medu           int64
Fedu           int64
Mjob          object
Fjob          object
reason        object
guardian      object
traveltime     int64
studytime      int64
failures       int64
schoolsup     object
famsup        object
paid          object
activities    object
nursery       object
higher        object
internet      object
romantic      object
famrel         int64
freetime       int64
goout          int64
Dalc           int64
Walc           int64
health         int64
absences       int64
G1             int64
G2             int64
G3             int64
dtype: object
Hours_Studied                  int64
Attendance                     int64
Parental_Involvement          object
Access_to_Resources           object
Extracurricular_Activities    object
Sleep_Hours                    int64
Previous_Scores                int64
Motivation_Level              object
Internet_Access               object
Tutoring_Sessions              int64
Family_Income                 object
Teacher_Quality               object
School_Type                   object
Peer_Influence                object
Physical_Activity              int64
Learning_Disabilities         object
Parental_Education_Level      object
Distance_from_Home            object
Gender                        object
Exam_Score                     int64
dtype: object

In [31]:
print("========== Numerical Columns ==========")

print("Maths:", len(math_df.select_dtypes(include='number').columns))

print("Portuguese:", len(port_df.select_dtypes(include='number').columns))

print("Performance Factors:", len(factor_df.select_dtypes(include='number').columns))

========== Numerical Columns ==========
Maths: 16
Portuguese: 16
Performance Factors: 7

In [32]:
print("========== Categorical Columns ==========")

print("Maths:", len(math_df.select_dtypes(include='object').columns))

print("Portuguese:", len(port_df.select_dtypes(include='object').columns))

print("Performance Factors:", len(factor_df.select_dtypes(include='object').columns))

========== Categorical Columns ==========
Maths: 17
Portuguese: 17
Performance Factors: 13

In [33]:
print("========== Unique Values ==========")

for col in math_df.columns:
    print(col, ":", math_df[col].nunique())

========== Unique Values ==========
school : 2
sex : 2
age : 8
address : 2
famsize : 2
Pstatus : 2
Medu : 5
Fedu : 5
Mjob : 5
Fjob : 5
reason : 4
guardian : 3
traveltime : 4
studytime : 4
failures : 4
schoolsup : 2
famsup : 2
paid : 2
activities : 2
nursery : 2
higher : 2
internet : 2
romantic : 2
famrel : 5
freetime : 5
goout : 5
Dalc : 5
Walc : 5
health : 5
absences : 34
G1 : 17
G2 : 17
G3 : 18

In [34]:
for col in port_df.columns:
    print(col, ":", port_df[col].nunique())

school : 2
sex : 2
age : 8
address : 2
famsize : 2
Pstatus : 2
Medu : 5
Fedu : 5
Mjob : 5
Fjob : 5
reason : 4
guardian : 3
traveltime : 4
studytime : 4
failures : 4
schoolsup : 2
famsup : 2
paid : 2
activities : 2
nursery : 2
higher : 2
internet : 2
romantic : 2
famrel : 5
freetime : 5
goout : 5
Dalc : 5
Walc : 5
health : 5
absences : 24
G1 : 17
G2 : 16
G3 : 17

In [35]:
for col in factor_df.columns:
    print(col, ":", factor_df[col].nunique())

Hours_Studied : 41
Attendance : 41
Parental_Involvement : 3
Access_to_Resources : 3
Extracurricular_Activities : 2
Sleep_Hours : 7
Previous_Scores : 51
Motivation_Level : 3
Internet_Access : 2
Tutoring_Sessions : 9
Family_Income : 3
Teacher_Quality : 3
School_Type : 2
Peer_Influence : 3
Physical_Activity : 7
Learning_Disabilities : 2
Parental_Education_Level : 3
Distance_from_Home : 3
Gender : 2
Exam_Score : 45

In [36]:
math_df.columns.equals(port_df.columns)

True

In [37]:
print(math_df.columns.equals(port_df.columns))

True

In [38]:
merged_students = pd.concat(
    [math_df, port_df],
    ignore_index=True
)

In [40]:
print(merged_students.shape)
display(merged_students.head())

(1048, 33)

,school,sex,age,address,famsize,Pstatus,Medu,Fedu,Mjob,Fjob,...,famrel,freetime,goout,Dalc,Walc,health,absences,G1,G2,G3
0,GP,F,18,U,GT3,A,4,4,at_home,teacher,...,4,3,4,1,1,3,6,5,6,6
1,GP,F,17,U,GT3,T,1,1,at_home,other,...,5,3,3,1,1,3,4,5,5,6
2,GP,F,15,U,LE3,T,1,1,at_home,other,...,4,3,2,2,3,3,10,7,8,10
3,GP,F,15,U,GT3,T,4,2,health,services,...,3,2,2,1,1,5,2,15,14,15
4,GP,F,16,U,GT3,T,3,3,other,other,...,4,3,2,1,2,5,4,6,10,10

In [41]:
merged_students.to_csv(
    "/content/drive/MyDrive/Student_Performance_Project/data/processed/StudentPerformance.csv",
    index=False
)

OSError: Cannot save file into a non-existent directory: '/content/drive/MyDrive/Student_Performance_Project/data/processed'

In [42]:
import os

os.makedirs(
    "/content/drive/MyDrive/Student_Performance_Project/data/processed",
    exist_ok=True
)

In [43]:
merged_students.to_csv(
    "/content/drive/MyDrive/Student_Performance_Project/data/processed/StudentPerformance.csv",
    index=False
)

In [44]:
import pandas as pd

student_df = pd.concat([math_df, port_df], ignore_index=True)

In [45]:
student_df["Student_ID"] = range(1, len(student_df)+1)
factor_df["Student_ID"] = range(1, len(factor_df)+1)

In [46]:
factor_df = factor_df.iloc[:len(student_df)]

In [47]:
merged_df = pd.merge(
    student_df,
    factor_df,
    on="Student_ID",
    how="inner"
)

In [48]:
factor_df = factor_df.rename(columns={
    "Gender":"Gender_Factors",
    "Internet_Access":"Internet_Access_Factors"
})

In [49]:
merged_df.to_csv(
"/content/drive/MyDrive/Student_Performance_Project/data/processed/FinalMergedDataset.csv",
index=False)